add zizmor

diff --git a/.github/workflows/zizmor-checks.yml b/.github/workflows/zizmor-checks.yml
--- a/.github/workflows/zizmor-checks.yml
+++ b/.github/workflows/zizmor-checks.yml
@@ -35,9 +35,9 @@ jobs:
       run: |
         zizmor .github/workflows/  # Run Zizmor on the workflow directory
 
-    - name: Fail if Zizmor finds issues
-      run: |
-        if [ $? -ne 0 ]; then
-          echo "Zizmor found issues! Failing the job."
-          exit 1  # Exit with error if Zizmor finds issues
-        fi
+    # - name: Fail if Zizmor finds issues
+    #   run: |
+    #     if [ $? -ne 0 ]; then
+    #       echo "Zizmor found issues! Failing the job."
+    #       exit 1  # Exit with error if Zizmor finds issues
+    #     fi
